arch: 
  - ppc64le
  - amd64
  
language: erlang

os: linux

dist: xenial

before_install:
  - pip install --user cpp-coveralls coveralls-merge
  - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then sudo apt-get update; sudo apt-get install rebar; fi

install:
  - rebar get-deps

script: rebar compile && rebar skip_deps=true eunit

otp_release:
  - 19.0
  - 22.3
  - 23.0
# Disable otp_release 19.0 as this release is not supported on Ubuntu16.04 for arch: ppc64le
jobs: 
  exclude:
    - arch: ppc64le
      otp_release: 19.0
      
after_success:
  - cpp-coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - coveralls-merge c.json erlang.json
